### ISSUE TITLE
Login Funktion

### ISSUE THREAD

**Issue by amadeus0505** [amadeus0505/PSoC-Forum#1]
## Der Benutzer soll sich einloggen können.

**OK:**
- Benutzer kann nach dem Einloggen Beiträge und Kommentare posten können.

**NOK:**
- Fehlercode
- Benutzer kann keine Kommentare/Beiträge posten

**Comment by amadeus0505** [comment]
Login Funktion wurde eingerichtet.

Noch keine Implementierung der Datenbank -> Statische Funktion zum Überprüfen des Passwortes

**Comment by B-Walch** [comment]
2,5 von 2,5 Punkten
